M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 27 May 2023 01:06:42 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-27T01:06:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X69.225Y-71.4
X69.225Y-78.2
T2
X70.25Y-56.5
X70.25Y-82.75
T0
M30
